### PR TITLE
implement read-only calls for releases endpoint

### LINKED ISSUE #270: Add support for releases
I am happy to help implement this, but there are pull requests in the queue that are several weeks old. The last commit was over a month ago. Is this library actively maintained?

### PR DESCRIPTION
**Pull request by womfoo**
partially fixes #270

### CODE REVIEW

**Comment by phadej** [comment]
Can you rebase on current master, I would like to have Travis green.

**Comment by womfoo** [comment]
Pushed fresh rebase from master.

**Comment by womfoo** [comment]
Builds on travis now green but its still yellow on github for some reason.

**Comment by phadej** [comment]
Thanks!

**Comment by womfoo** [comment]
Thanks for merging!

**Comment by matthew-piziak** [comment]
Thanks for this!

**Comment by womfoo** [comment]
@matthew-piziak glad I could help!

**Pull request merged**
