### PR TITLE
Add PullRequestOptions

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by filib** [comment]
@phadej ah nice one! I was just gonna take a stab at this one today!

**Comment by phadej** [comment]
@filib please try it out, and comment if something could be better

**Comment by filib** [comment]
@phadej so far, so good for my needs.

**Comment by phadej** [comment]
Nice to hear, please comment if something is inconvenient in the API, e.g. you use some helper all over the place. Regarding this or anything in the library.

**Pull request merged**
