### PR TITLE
Decouple requests creation from execution

### PR DESCRIPTION
**Pull request by phadej**
An example approach to https://github.com/jwiegley/github/issues/127

Please comment, changing the rest endpoints is straightforward. But as it's time consuming, I won't do it before green light.

After transformation is complete, `Github.Private` could be cleaned up.

### CODE REVIEW

**Comment by jwiegley** [comment]
@phadej How would you like to become the maintainer of this package, Oleg? Then it would be your decision how best to migrate to the new strategy.

**Comment by phadej** [comment]
@jwiegley I'd be happy to

**Comment by jwiegley** [comment]
@phadej You've been added as a collaborator.  If you'd like, just delete your fork of this repository, and I will transfer ownership to you. Then you can update the .cabal file to point to your URL and upload a new version.

**Comment by phadej** [comment]
@jwiegley done

**Comment by phadej** [comment]
Please remember to add me as maintainer to hackage

**Comment by jwiegley** [comment]
@phadej GitHub is transferring ownership as we speak. I'll make an owner on Hackage too.

**Comment by phadej** [comment]
Thanks, :+1:

**Comment by jwiegley** [comment]
@phadej You are officially the new maintainer! Thank you!

**Pull request merged**
