### PR TITLE
fixup to work with stackage 13.15

### PR DESCRIPTION
**Pull request by shmish111**

### CODE REVIEW

**Comment by phadej** [comment]
As you can see from travis build, this is a bad idea.

**Comment by shmish111** [comment]
How can we get this working with a recent LTS package set? Now that the PR is closed I can't see the travis build.

**Comment by phadej** [comment]
If you click red-cross next to the commit, you'll see the link to https://travis-ci.org/phadej/github/builds/543669336

---

starting with

```
resolver: lts-13.23
packages: [.]
```

stack reports

```
In the dependencies for github-0.22:
    binary-instances must match >=1 && <1.1, but the stack configuration has no specified version  (latest matching version is 1)
    unordered-containers-0.2.9.0 from stack configuration does not match >=0.2.10.0 && <0.3  (latest matching version is 0.2.10.0)
```

so let's fix that

Second try

```
resolver: lts-13.23
packages: [.]
extra-deps:
- binary-instances-1
- unordered-containers-0.2.10.0
```

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for binary-instances-1:
    binary-orphans-0.1.8.0 from stack configuration does not match >=1.0.1 && <1.1  (latest matching version is 1.0.1)
    time-compat-0.1.0.3 from stack configuration does not match >=1.9.2.2 && <1.10  (latest matching version is 1.9.2.2)
needed due to github-0.22 -> binary-instances-1
```

Third try:

```
resolver: lts-13.23
packages: [.]
extra-deps:
- binary-instances-1
- unordered-containers-0.2.10.0
- time-compat-1.9.2.2
- binary-orphans-1.0.1
```

Success, `stack` starts to build things.

---

Or:
- use `github` which is in the snapshot (lts-12 has `github-0.19`, I don't know why `github` isn't in lts-13)
- don't use `stack` if this manual process feels stupid.

**Comment by shmish111** [comment]
Thanks, I love the intuitive github UI 😒

I'm aware of this process, the problem is that the version bounds are very restrictive and are causing issues with other libraries, in my case https://github.com/tsani/servant-github-webhook. Can some of these lower bounds be dropped? I can see from travis that `binary-instances-1` needs to be used rather than just orphans.

I will create another PR that only has changes to the lower bounds

**Pull request closed without merging**
